window.MEAL_DATA = {
  "weeks": [
    {
      "start": "2026-09-01",
      "end": "2026-09-07",
      "days": [
        {"date":"2026-09-01","lunch":{"name":"Pollo al horno con patatas","items":[{"name":"Pechuga de pollo","qty":"140 g"},{"name":"Patata","qty":"400 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Arroz con merluza y verduras","items":[{"name":"Arroz","qty":"90 g"},{"name":"Merluza","qty":"150 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-02","lunch":{"name":"Arroz con pollo","items":[{"name":"Arroz","qty":"120 g"},{"name":"Pechuga de pollo","qty":"130 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Salmón con patata","items":[{"name":"Patata","qty":"400 g"},{"name":"Salmón","qty":"140 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Pan","qty":"40 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-03","lunch":{"name":"Garbanzos con arroz y verduras","items":[{"name":"Garbanzos cocidos","qty":"250 g"},{"name":"Arroz","qty":"60 g"},{"name":"Verdura variada","qty":"250 g"},{"name":"Huevo","qty":"1 ud"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Pasta con ternera","items":[{"name":"Pasta","qty":"90 g"},{"name":"Ternera magra","qty":"120 g"},{"name":"Tomate","qty":"150 g"},{"name":"Verdura variada","qty":"150 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-04","lunch":{"name":"Pasta con ternera","items":[{"name":"Pasta","qty":"120 g"},{"name":"Ternera magra","qty":"120 g"},{"name":"Tomate","qty":"150 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Arroz con atún","items":[{"name":"Arroz","qty":"100 g"},{"name":"Atún al natural escurrido","qty":"120 g"},{"name":"Tomate + verdura","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-05","lunch":{"name":"Paella de pollo y gambas","items":[{"name":"Arroz","qty":"120 g"},{"name":"Pollo","qty":"100 g"},{"name":"Gambas","qty":"80 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Pollo con patata","items":[{"name":"Patata","qty":"350 g"},{"name":"Pechuga de pollo","qty":"140 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Pan","qty":"40 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-06","lunch":{"name":"Arroz con pollo","items":[{"name":"Arroz","qty":"120 g"},{"name":"Pechuga de pollo","qty":"130 g"},{"name":"Verdura cocida","qty":"100 g"},{"name":"Aceite de oliva","qty":"5 g"},{"name":"Pan","qty":"40 g"},{"name":"Plátano","qty":"1 ud"}]},"dinner":{"name":"Cena con amigos","items":[{"name":"Hamburguesa o kebab","qty":"1 ración"}]}},
        {"date":"2026-09-07","lunch":{"name":"Lasaña casera","items":[{"name":"Láminas de pasta","qty":"90 g"},{"name":"Ternera magra","qty":"120 g"},{"name":"Tomate","qty":"150 g"},{"name":"Leche para bechamel","qty":"150 ml"},{"name":"Queso","qty":"30 g"},{"name":"Ensalada","qty":"1 ración"}]},"dinner":{"name":"Merluza con patata","items":[{"name":"Patata","qty":"350 g"},{"name":"Merluza","qty":"150 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Yogur natural","qty":"125 g"}]}}
      ],
      "shopping": [
        {"category":"Carne y pescado","name":"Pechuga de pollo","qty":"650–700 g"},{"category":"Carne y pescado","name":"Ternera magra","qty":"360–400 g"},{"category":"Carne y pescado","name":"Merluza","qty":"300 g"},{"category":"Carne y pescado","name":"Salmón","qty":"150 g"},{"category":"Carne y pescado","name":"Atún al natural","qty":"2 latas grandes"},{"category":"Carne y pescado","name":"Gambas","qty":"100 g"},
        {"category":"Hidratos","name":"Arroz","qty":"650 g"},{"category":"Hidratos","name":"Pasta + láminas de lasaña","qty":"350–500 g"},{"category":"Hidratos","name":"Patatas","qty":"1,5 kg"},{"category":"Hidratos","name":"Pan","qty":"150–250 g"},
        {"category":"Otros","name":"Garbanzos cocidos","qty":"1 bote grande"},{"category":"Otros","name":"Huevos","qty":"6 uds"},{"category":"Otros","name":"Yogur natural","qty":"6 uds de 125 g"},{"category":"Otros","name":"Leche","qty":"250 ml"},{"category":"Otros","name":"Queso","qty":"50 g"},
        {"category":"Fruta y verdura","name":"Verdura variada","qty":"2,5 kg"},{"category":"Fruta y verdura","name":"Tomate / salsa de tomate","qty":"500 g"},{"category":"Fruta y verdura","name":"Fruta variada","qty":"5 uds"},{"category":"Fruta y verdura","name":"Plátano","qty":"1 ud"},{"category":"Fruta y verdura","name":"Ensalada","qty":"1 bolsa"},{"category":"Despensa","name":"Aceite de oliva","qty":"100 ml"}
      ]
    },
    {
      "start": "2026-09-08",
      "end": "2026-09-14",
      "days": [
        {"date":"2026-09-08","lunch":{"name":"Arroz con pollo","items":[{"name":"Arroz","qty":"100 g"},{"name":"Pechuga de pollo","qty":"140 g"},{"name":"Verdura variada","qty":"250 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Tortilla con patata","items":[{"name":"Huevos","qty":"3 uds"},{"name":"Patata","qty":"300 g"},{"name":"Ensalada","qty":"1 ración"},{"name":"Pan","qty":"60 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-09","lunch":{"name":"Pasta con pollo","items":[{"name":"Pasta","qty":"120 g"},{"name":"Pechuga de pollo","qty":"130 g"},{"name":"Tomate","qty":"150 g"},{"name":"Verdura variada","qty":"150 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Arroz con salmón","items":[{"name":"Arroz","qty":"100 g"},{"name":"Salmón","qty":"140 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-10","lunch":{"name":"Lentejas con arroz y verduras","items":[{"name":"Lentejas cocidas","qty":"250 g"},{"name":"Arroz","qty":"60 g"},{"name":"Verdura variada","qty":"250 g"},{"name":"Huevo","qty":"1 ud"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Ternera con patata","items":[{"name":"Patata","qty":"350 g"},{"name":"Ternera magra","qty":"130 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Pan","qty":"40 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-11","lunch":{"name":"Arroz con pollo o pavo","items":[{"name":"Arroz","qty":"120 g"},{"name":"Pollo o pavo","qty":"130 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Pasta con atún","items":[{"name":"Pasta","qty":"100 g"},{"name":"Atún al natural escurrido","qty":"120 g"},{"name":"Tomate","qty":"150 g"},{"name":"Verdura variada","qty":"150 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-12","lunch":{"name":"Pasta con ternera","items":[{"name":"Pasta","qty":"110 g"},{"name":"Ternera magra","qty":"120 g"},{"name":"Tomate","qty":"150 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Pollo al horno con patatas","items":[{"name":"Pechuga de pollo","qty":"150 g"},{"name":"Patata","qty":"400 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Pan","qty":"40 g"},{"name":"Yogur natural","qty":"125 g"}]}},
        {"date":"2026-09-13","lunch":{"name":"Pasta con pollo","items":[{"name":"Pasta","qty":"120 g"},{"name":"Pechuga de pollo","qty":"130 g"},{"name":"Tomate suave","qty":"100 g"},{"name":"Aceite de oliva","qty":"5 g"},{"name":"Pan","qty":"40 g"},{"name":"Plátano","qty":"1 ud"}]},"dinner":{"name":"Cena con amigos","items":[{"name":"Hamburguesa o kebab","qty":"1 ración"}]}},
        {"date":"2026-09-14","lunch":{"name":"Garbanzos con patata y verduras","items":[{"name":"Garbanzos cocidos","qty":"250 g"},{"name":"Patata","qty":"300 g"},{"name":"Verdura variada","qty":"250 g"},{"name":"Huevos","qty":"2 uds"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Fruta","qty":"1 ud"}]},"dinner":{"name":"Arroz con merluza","items":[{"name":"Arroz","qty":"90 g"},{"name":"Merluza","qty":"160 g"},{"name":"Verdura variada","qty":"200 g"},{"name":"Aceite de oliva","qty":"10 g"},{"name":"Yogur natural","qty":"125 g"}]}}
      ],
      "shopping": [
        {"category":"Carne y pescado","name":"Pechuga de pollo/pavo","qty":"700 g"},{"category":"Carne y pescado","name":"Ternera magra","qty":"250–300 g"},{"category":"Carne y pescado","name":"Merluza","qty":"200 g"},{"category":"Carne y pescado","name":"Salmón","qty":"150 g"},{"category":"Carne y pescado","name":"Atún al natural","qty":"2 latas grandes"},
        {"category":"Hidratos","name":"Arroz","qty":"500 g"},{"category":"Hidratos","name":"Pasta","qty":"500 g"},{"category":"Hidratos","name":"Patatas","qty":"1,4–1,5 kg"},{"category":"Hidratos","name":"Pan","qty":"200–250 g"},
        {"category":"Otros","name":"Lentejas cocidas","qty":"1 bote grande"},{"category":"Otros","name":"Garbanzos cocidos","qty":"1 bote grande"},{"category":"Otros","name":"Huevos","qty":"6 uds"},{"category":"Otros","name":"Yogur natural","qty":"6 uds de 125 g"},
        {"category":"Fruta y verdura","name":"Verdura variada","qty":"2,5 kg"},{"category":"Fruta y verdura","name":"Tomate / salsa de tomate","qty":"600 g"},{"category":"Fruta y verdura","name":"Fruta variada","qty":"6 uds"},{"category":"Fruta y verdura","name":"Plátano","qty":"1 ud"},{"category":"Fruta y verdura","name":"Ensalada","qty":"1 bolsa"},{"category":"Despensa","name":"Aceite de oliva","qty":"100 ml"}
      ]
    }
  ]
};